# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check with mypy
      run: |
        if [[ "${{ matrix.python-version }}" = "3.11" ]]
        then
          # --pre needed for Python 3.11 which doesn't have wheels (and may not
          # be fully supported) in version 2.1.2. Once 2.1.3 is released this
          # can be removed. Due to https://github.com/pygame/pygame/issues/3572
          # we can't apply this for all Python versions.
          pip install --pre pygame  # Needed for examples
        else
          pip install pygame   # Needed for examples
        fi
        mypy pythonosc examples
    - name: Test with pytest
      run: |
        pytest
